name: "Auto Release"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions: write-all
    name: "Build & Release"
    steps:
      - name: "Build & Release"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            target/*.jar
